/**
 * Accommodation record composer (M3) — pure, unit-testable.
 *
 * Produces the user-configured accommodation record: a concrete document an
 * organization can point procurement at, in place of a vague "AI is
 * accessible" claim. HONESTY RULES baked in:
 *  - no certification language — this is supporting documentation, and
 *    accommodation decisions are made case-by-case by organizations;
 *  - zero content leakage — settings and the user's own notes only, never
 *    vault/conversation/draft content;
 *  - states only features that actually ship.
 *
 * Mirror of packages/obsidian/src/accommodation.ts (same content contract,
 * surface-specific lines differ) — consolidate into @rpcs1/core if a third
 * surface ever needs it.
 */

import { clampResponseDelay, normalizeTextScale, type LoopPrefs } from './loop-prefs';

export const NOTES_MAX_CHARS = 2000;

const SCALE_LABEL: Record<string, string> = {
  default: 'Default',
  large: 'Large',
  larger: 'Larger',
};

function pacingLabel(ms: number): string {
  const v = clampResponseDelay(ms);
  if (v === 0) return 'Instant';
  return `Results appear no sooner than ${v / 1000} second${v === 1000 ? '' : 's'} after asking`;
}

export function composeAccommodationRecord(
  prefs: LoopPrefs,
  meta: { surface: string; date: string; version?: string },
): string {
  const notes = (prefs.notes ?? '').trim();
  return [
    '# Accommodation record — Explicit Formula',
    '',
    `Generated: ${meta.date} · Surface: ${meta.surface}` +
      (meta.version ? ` · Version: ${meta.version}` : ''),
    '',
    'This is a user-configured record of the accessibility settings currently in',
    'active use, generated by the user from inside the product. It is suitable as',
    'supporting documentation for an accommodation request. It contains no notes,',
    'vault, or conversation content — settings and the user’s own words only.',
    '',
    '## Settings in active use',
    '',
    `- Panel text size: ${SCALE_LABEL[normalizeTextScale(prefs.textScale)]}`,
    `- Response pacing: ${pacingLabel(prefs.responseDelayMs)}`,
    '- Input: keyboard text entry; OS keyboard dictation (voice) available on mobile devices',
    '',
    '## User notes',
    '',
    notes.length > 0 ? notes.slice(0, NOTES_MAX_CHARS) : '(none provided)',
    '',
    '## Provided to all users, no configuration required',
    '',
    '- Interpretation is shown as lockable lines; nothing is sent or saved without explicit confirmation',
    '- Screen-reader announcements (polite, non-interrupting) for every step of the loop',
    '- Every action has a button — no gesture is ever required',
    '- Touch targets of at least 44px on mobile; locked state is never shown by color alone',
    '- Offline capture: a brain dump typed while offline is saved on-device and recoverable',
    '- Configurable response pacing implemented as a minimum time-to-result (a slow connection already counts toward it)',
    '',
  ].join('\n');
}
