/**
 * License key generation and verification using JWT (jose).
 *
 * Keys are generated by the Stripe webhook on successful payment,
 * emailed to the customer, and validated by the SDK on each API call.
 *
 * No database needed — the key IS the entitlement record.
 */

import { SignJWT, jwtVerify } from 'jose';
import { env } from './env';

export type Tier = 'indie' | 'team';

export interface LicenseClaims {
  email: string;
  tier: Tier;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  issuedAt: number;
}

function secret(): Uint8Array {
  return new TextEncoder().encode(env.LICENSE_JWT_SECRET);
}

/**
 * Generate a signed license key JWT.
 * Called from the Stripe webhook after successful checkout.
 */
export async function generateLicenseKey(claims: LicenseClaims): Promise<string> {
  return new SignJWT({
    email: claims.email,
    tier: claims.tier,
    cid: claims.stripeCustomerId,
    sid: claims.stripeSubscriptionId,
  })
    .setProtectedHeader({ alg: 'HS256' })
    .setIssuedAt(claims.issuedAt)
    .setIssuer('rpcs1.dev')
    .setSubject(claims.email)
    .sign(secret());
}

/**
 * Verify a license key JWT and return its claims.
 * Returns null if the key is invalid or expired.
 */
export async function verifyLicenseKey(token: string): Promise<LicenseClaims | null> {
  try {
    const { payload } = await jwtVerify(token, secret(), {
      issuer: 'rpcs1.dev',
    });
    return {
      email:                  payload.sub as string,
      tier:                   payload['tier'] as Tier,
      stripeCustomerId:       payload['cid'] as string,
      stripeSubscriptionId:   payload['sid'] as string,
      issuedAt:               payload.iat as number,
    };
  } catch {
    return null;
  }
}

/**
 * Check if a request has a valid paid-tier license key.
 * Accepts the key from the Authorization header or x-license-key header.
 */
export async function getLicenseFromRequest(
  req: Request,
): Promise<LicenseClaims | null> {
  const auth = req.headers.get('authorization');
  const direct = req.headers.get('x-license-key');

  const token = direct ?? (auth?.startsWith('Bearer ') ? auth.slice(7) : null);
  if (!token) return null;

  return verifyLicenseKey(token);
}
