/**
 * License key generation and verification using JWT (jose).
 *
 * Keys are generated by the Stripe webhook on each PAID invoice (first
 * payment and every renewal), emailed to the customer, and verified
 * server-side on each hosted-API call.
 *
 * No database needed — the key IS the entitlement record. Expiry is carried
 * in the token itself (`exp` = the Stripe billing-period end), so a canceled
 * subscription's key stops validating when the paid period ends, with no
 * revocation list to maintain.
 */

import { SignJWT, jwtVerify } from 'jose';
import { env } from './env';

export type Tier = 'indie' | 'team';

export interface LicenseClaims {
  email: string;
  tier: Tier;
  stripeCustomerId: string;
  stripeSubscriptionId: string;
  issuedAt: number;
  /** unix seconds — Stripe subscription.current_period_end */
  expiresAt: number;
}

function secret(): Uint8Array {
  return new TextEncoder().encode(env.LICENSE_JWT_SECRET);
}

/**
 * Generate a signed license key JWT.
 * Called from the Stripe webhook after a paid invoice.
 */
export async function generateLicenseKey(claims: LicenseClaims): Promise<string> {
  return new SignJWT({
    email: claims.email,
    tier: claims.tier,
    cid: claims.stripeCustomerId,
    sid: claims.stripeSubscriptionId,
  })
    .setProtectedHeader({ alg: 'HS256' })
    .setIssuedAt(claims.issuedAt)
    .setExpirationTime(claims.expiresAt)
    .setIssuer('rpcs1.dev')
    .setSubject(claims.email)
    .sign(secret());
}

/**
 * Verify a license key JWT and return its claims.
 * Returns null if the key is invalid, expired, or missing an `exp` claim.
 *
 * jose's jwtVerify enforces `exp` automatically; `requiredClaims: ['exp']`
 * additionally rejects legacy keys that were issued without an expiry.
 */
export async function verifyLicenseKey(token: string): Promise<LicenseClaims | null> {
  try {
    const { payload } = await jwtVerify(token, secret(), {
      issuer: 'rpcs1.dev',
      requiredClaims: ['exp'],
      clockTolerance: 60,
    });
    return {
      email:                  payload.sub as string,
      tier:                   payload['tier'] as Tier,
      stripeCustomerId:       payload['cid'] as string,
      stripeSubscriptionId:   payload['sid'] as string,
      issuedAt:               payload.iat as number,
      expiresAt:              payload.exp as number,
    };
  } catch {
    return null;
  }
}

/**
 * Check if a request has a valid paid-tier license key.
 * Accepts the key from the Authorization header or x-license-key header.
 */
export async function getLicenseFromRequest(
  req: Request,
): Promise<LicenseClaims | null> {
  const auth = req.headers.get('authorization');
  const direct = req.headers.get('x-license-key');

  const token = direct ?? (auth?.startsWith('Bearer ') ? auth.slice(7) : null);
  if (!token) return null;

  return verifyLicenseKey(token);
}
