// ── Accommodation record composer (M3) — pure: no Obsidian imports ────────────
//
// Produces the user-configured accommodation record as an ordinary vault note:
// a concrete document an organization can point procurement at. Honesty rules
// baked in: no certification language (accommodation decisions are made
// case-by-case by organizations); ZERO vault leakage — the record includes
// settings and the user's own notes, never folder names, endpoints, note
// content, or session content.
//
// Mirror of packages/web/lib/accommodation.ts (same content contract,
// surface-specific lines differ).

import { clampResponseDelay, normalizeTextScale } from './ui-prefs.js';

export const NOTES_MAX_CHARS = 2000;

const SCALE_LABEL: Record<string, string> = {
  default: 'Default',
  large: 'Large',
  larger: 'Larger',
};

function pacingLabel(ms: number): string {
  const v = clampResponseDelay(ms);
  if (v === 0) return 'Instant';
  return `Results appear no sooner than ${v / 1000} second${v === 1000 ? '' : 's'} after asking`;
}

export interface AccommodationInputs {
  textScale: unknown;
  responseDelayMs: number;
  sessionNotesEnabled: boolean;
  learningsEnabled: boolean;
  accommodationNotes: string;
}

export function composeAccommodationRecord(
  s: AccommodationInputs,
  meta: { version: string; date: string },
): string {
  const notes = (s.accommodationNotes ?? '').trim();
  return [
    '# Accommodation record — Explicit Formula',
    '',
    `Generated: ${meta.date} · Surface: Obsidian plugin (desktop and mobile) · Version: ${meta.version}`,
    '',
    'This is a user-configured record of the accessibility settings currently in',
    'active use, generated by the user from inside the product. It is suitable as',
    'supporting documentation for an accommodation request. It contains no vault',
    'content, folder names, or conversation content — settings and the user’s own',
    'words only.',
    '',
    '## Settings in active use',
    '',
    `- Panel text size: ${SCALE_LABEL[normalizeTextScale(s.textScale)]}`,
    `- Response pacing: ${pacingLabel(s.responseDelayMs)}`,
    `- Session write-backs to the vault: ${s.sessionNotesEnabled ? 'on' : 'off'} · Learnings tracking: ${s.learningsEnabled ? 'on' : 'off'}`,
    '- Input: keyboard text entry; OS keyboard dictation (voice) available on mobile devices',
    '',
    '## User notes',
    '',
    notes.length > 0 ? notes.slice(0, NOTES_MAX_CHARS) : '(none provided)',
    '',
    '## Provided to all users, no configuration required',
    '',
    '- All data lives in the user’s own vault as ordinary, editable, deletable files',
    '- Vault reading is off by default; every round shows exactly what left the machine',
    '- Interpretation is shown as lockable lines; nothing is saved without explicit confirmation',
    '- Screen-reader announcements (polite, non-interrupting) for every step of the loop',
    '- Every action has a button — no gesture is ever required',
    '- Touch targets of at least 44px on mobile; locked state is never shown by color alone',
    '- Configurable response pacing implemented as a minimum time-to-result (a slow connection already counts toward it)',
    '',
  ].join('\n');
}
